#!/bin/bash

cppcheck --error-exitcode=9 --inline-suppr --suppress=duplicateExpression --suppress=missingIncludeSystem -I . -I /usr/local/include  --enable=all animate.cpp || exit 1

if [[ "$1" == "debug" ]]; then
    CPPOPT="-Og -g"
    shift
else
    CPPOPT="-O3"
fi
g++ ${CPPOPT} -Wall -Werror -o animate animate.cpp -l raylib -l pthread -l dl || exit 1

./animate $1 || exit 1
exit 0
